const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');
const root=path.resolve(__dirname,'..');const sandbox={window:{}};vm.createContext(sandbox);
['data/songs.js','data/archive-catalog.js','data/radio-intents.js','data/2026-08-25-uploads.js','data/briefing.js','data/2026-08-26-uploads.js','data/2026-08-27-uploads.js','data/2026-08-29-uploads.js'].forEach(file=>vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),sandbox,{filename:file}));
const songs=sandbox.window.CMD_SONGS,feed=sandbox.window.CMD_BRIEFING,profiles=sandbox.window.CMD_RADIO_CONFIG.profiles;const read=file=>fs.readFileSync(path.join(root,file),'utf8');

test('August 29 upload families stay together',()=>{const ids=['cloudlife','her-perfume-rides-shotgun','keep-moving','thirty-six','one-brick','where-monsters-are','make-me-an-animal','fractured-face'];const by=Object.fromEntries(ids.map(id=>[id,songs.find(song=>song.id===id)]));ids.forEach(id=>assert.ok(by[id],id));assert.deepEqual(Array.from(by.cloudlife.variants,v=>v.id),['life-of-a-cloud','r-and-b-mix']);assert.match(by.cloudlife.lineage,/rainy stretch in Red Deer/);assert.deepEqual(Array.from(by['her-perfume-rides-shotgun'].variants,v=>v.id),['power-ballad-dubstep-drop','v2-remastered']);assert.deepEqual(Array.from(by['keep-moving'].variants,v=>v.id),['v2','trap-mix']);assert.deepEqual(Array.from(by['thirty-six'].variants,v=>v.id),['main']);assert.ok(by['thirty-six'].aliases.includes('Running Out of Versions'));assert.deepEqual(Array.from(by['one-brick'].variants,v=>v.id),['barbershop-dubstep-acappella','extended-v1']);assert.deepEqual(Array.from(by['where-monsters-are'].variants,v=>v.id),['dnb-folk-tale','monster-and-maiden','monster-and-maiden-alt']);assert.match(by['where-monsters-are'].lineage,/unconfirmed/);assert.deepEqual(Array.from(by['make-me-an-animal'].variants,v=>v.id),['edm-switch-up-mix','late-night-warehouse-remastered']);assert.deepEqual(Array.from(by['fractured-face'].variants,v=>v.id),['may-2026-remastered']);assert.equal(new Set(songs.map(song=>song.id)).size,songs.length);});

test('August 29 songs have radio profiles',()=>{assert.equal(profiles['fractured-face'].surprise,90);assert.equal(profiles.cloudlife.think,90);assert.equal(profiles['her-perfume-rides-shotgun'].heavy,88);assert.equal(profiles['keep-moving']['level-up'],100);assert.equal(profiles['thirty-six'].think,100);});

test('August 29 feed entries are ordered and shareable',()=>{assert.equal(feed.entries[0].id,'release-fractured-face');assert.equal(feed.entries[0].featuredOrder,1);assert.equal(feed.entries.find(e=>e.id==='release-cloudlife').featuredOrder,2);assert.equal(feed.entries.find(e=>e.id==='release-her-perfume-rides-shotgun').featuredOrder,3);assert.equal(feed.entries.find(e=>e.id==='release-keep-moving').featuredOrder,4);assert.equal(feed.entries.find(e=>e.id==='release-thirty-six').featuredOrder,5);assert.equal(feed.entries.find(e=>e.id==='archive-wild-ways').featuredOrder,6);['release-fractured-face','make-me-an-animal-late-night-warehouse','her-perfume-v2-remastered','where-monsters-are-monster-and-maiden-alt','release-cloudlife','release-her-perfume-rides-shotgun','where-monsters-are-monster-and-maiden','release-keep-moving','release-thirty-six','one-brick-extended-v1'].forEach(id=>{const page=path.join(root,'updates',id,'index.html');assert.ok(fs.existsSync(page),`${id} needs a static update page`);const html=fs.readFileSync(page,'utf8');assert.match(html,/property="og:title"/);assert.match(html,/property="og:description"/);assert.match(html,/property="og:url"/);assert.ok(read('sitemap.xml').includes(`https://callmedaddy.musicsubject.com/updates/${id}/`));});});

test('August 29 raw uploads were moved into media folders',()=>{[' Keep Moving (Trap Mix) (1).mp3','keep moving (v2).mp3','Thirty Six (1).mp3','one brick at a time (EXTENDED v1) (1).mp3','Cloudlife (R&B Mix).mp3','Cloudlife (the life of a cloud) (1).mp3','Her Perfume Rides Shotgun (Power Ballad Dubstep Drop Mix).mp3','Where Monsters Are (Monster and Maiden).mp3','Where Monsters Are (Monster & Maiden) (1).mp3','animal day (late night warehouse mix) (Remastered) (1).mp3','fractured face (May 2026 Remastered).mp3','her perfume rides shotgun v2 (Remastered).mp3'].forEach(file=>assert.equal(fs.existsSync(path.join(root,file)),false,`${file} should not remain at repository root`));['media/songs/2026/08/where-monsters-are/monster-and-maiden-alt.mp3','media/songs/2026/08/make-me-an-animal/late-night-warehouse-remastered.mp3','media/songs/2026/08/fractured-face/may-2026-remastered.mp3','media/songs/2026/08/her-perfume-rides-shotgun/v2-remastered.mp3'].forEach(file=>assert.ok(fs.existsSync(path.join(root,file)),`${file} should exist`));assert.equal(fs.existsSync(path.join(root,'tmp-should-not-use.txt')),false);assert.equal(fs.existsSync(path.join(root,'updates/_dummy-never-use')),false);});

test('public entry points load the August 29 extension',()=>{['index.html','music/index.html','updates/index.html'].forEach(file=>assert.ok(read(file).includes('/data/2026-08-29-uploads.js?v=20260829-2'),`${file} needs the current August 29 uploads`));});
