(()=>{
  const audio=document.getElementById('pulseAudio'); if(!audio)return;
  const loadHelper=(src,key)=>new Promise(resolve=>{if(window[key])return resolve();const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=resolve;document.head.appendChild(s)});
  loadHelper('/persistent-site-browser.js?v=20260824-4','CMDPersistentSite');
  const gapReady=loadHelper('/silent-gap.js?v=20260823-1','CMD_SILENT_GAP');
  const sourceVideo=document.getElementById('sourceVideo'),play=document.getElementById('pulsePlay'),icon=document.getElementById('pulseIcon'),status=document.getElementById('pulseStatus'),progress=document.getElementById('pulseProgress'),bar=document.getElementById('pulseProgressBar'),current=document.getElementById('pulseCurrent'),duration=document.getElementById('pulseDuration'),player=document.getElementById('armandoPlayer'),trackCopy=player?.querySelector('.track-copy'),trackTitle=trackCopy?.querySelector('strong'),trackLabel=trackCopy?.querySelector('small'),cover=player?.querySelector('.armando-cover-button img'),machineArtist=player?.querySelector('.machine-meta span'),machineProject=player?.querySelector('.machine-meta b'),historyDrawer=document.querySelector('.armando-history-drawer');
  const songLink=document.createElement('a');songLink.className='cmd-now-song-link';songLink.textContent='Open this song →';songLink.hidden=true;trackCopy?.appendChild(songLink);
  const chosen={id:'did-armando-die-after-you-held-his-beer',title:'Did Armando Die After You Held His Beer?',artist:'MusicSubject × Call Me Daddy',project:'Armando',label:'Chosen version',audio:'/media/songs/2026/08/did-armando-die-after-you-held-his-beer/audio.mp3',cover:'/media/songs/2026/08/armando/cover.png',experience:'/power-pulse-uprising/'};
  const earlier={id:'armando',title:'Armando — Earlier Mix',artist:'MusicSubject × Call Me Daddy',project:'Armando archive',label:'Earlier Armando mix',audio:'/media/songs/2026/08/armando/audio.mp3',cover:'/media/songs/2026/08/armando/cover.png',experience:'/power-pulse-uprising/'};
  const catalog=(window.CMD_SONGS||[]).filter(s=>s?.audio&&!['armando','did-armando-die-after-you-held-his-beer'].includes(s.id)).map(s=>({id:s.id,title:s.title,artist:s.artist||'Call Me Daddy',project:s.project||'Catalog',label:'From the catalog',audio:s.audio,cover:s.cover||'',experience:s.experience||''}));
  const queue=[chosen,earlier,...catalog];let index=0,inGap=false,pending=-1,continuing=false;
  const fmt=s=>Number.isFinite(s)?`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`:'--:--';
  const sync=()=>{if(inGap)return;const d=audio.duration,r=d?audio.currentTime/d:0;if(bar)bar.style.width=`${r*100}%`;if(current)current.textContent=fmt(audio.currentTime);if(duration)duration.textContent=fmt(d);progress?.setAttribute('aria-valuenow',String(Math.round(r*100)))};
  const media=t=>{if(!('mediaSession'in navigator))return;try{navigator.mediaSession.metadata=new MediaMetadata({title:t.title,artist:t.artist,album:t.project,artwork:t.cover?[{src:new URL(t.cover,location.href).href}]:[]})}catch{}};
  const paint=t=>{if(trackTitle)trackTitle.textContent=t.title;if(trackLabel)trackLabel.textContent=t.label;if(machineArtist)machineArtist.textContent=t.artist;if(machineProject)machineProject.textContent=t.project.toUpperCase();if(cover&&t.cover){cover.src=t.cover;cover.alt=`${t.title} artwork`}const can=t.label==='From the catalog'&&t.experience;songLink.hidden=!can;if(can)songLink.href=t.experience;media(t)};
  const load=(i,auto=true)=>{inGap=false;pending=-1;index=Math.max(0,Math.min(queue.length-1,i));const t=queue[index];paint(t);audio.src=t.audio;audio.load();sync();window.CMDPersistentSite?.refreshClearance?.();if(status)status.textContent=auto?'Loading next…':'Tap artwork to play';if(auto)audio.play().catch(()=>{continuing=false;if(status)status.textContent='Tap artwork to continue'})};
  const gap=async()=>{if(index>=queue.length-1){continuing=false;if(status)status.textContent='End of the current catalog';if(icon)icon.textContent='▶';return}pending=index+1;continuing=true;if(status)status.textContent=`Next: ${queue[pending].title}…`;if(icon)icon.textContent='⋯';await gapReady;if(!window.CMD_SILENT_GAP){load(pending,true);return}inGap=true;audio.src=window.CMD_SILENT_GAP;audio.load();audio.play().catch(()=>load(pending,true))};
  const toggle=()=>{if(inGap){audio.pause();load(pending,false);return}if(audio.ended){audio.currentTime=0;audio.play().catch(()=>{});return}if(audio.paused){sourceVideo?.pause();audio.play().catch(()=>{})}else audio.pause()};
  play?.addEventListener('click',toggle);
  audio.addEventListener('play',()=>{sourceVideo?.pause();if(icon)icon.textContent=inGap?'⋯':'❚❚';if(!inGap&&status)status.textContent='Playing';player?.classList.toggle('is-playing',!inGap);if(!inGap)media(queue[index]);window.CMDPersistentSite?.setSession(true);window.CMDPersistentSite?.refreshClearance?.()});
  audio.addEventListener('pause',()=>{if(!inGap&&icon&&!audio.ended)icon.textContent='▶';if(!inGap&&status&&!audio.ended&&!continuing)status.textContent='Paused';if(!inGap)player?.classList.remove('is-playing')});
  audio.addEventListener('ended',()=>{if(inGap){const target=pending;inGap=false;load(target,true)}else{player?.classList.remove('is-playing');sync();gap()}});
  audio.addEventListener('loadedmetadata',sync);audio.addEventListener('timeupdate',sync);sourceVideo?.addEventListener('play',()=>{audio.pause()});
  progress?.addEventListener('click',e=>{if(inGap||!audio.duration)return;const r=progress.getBoundingClientRect();audio.currentTime=Math.max(0,Math.min(audio.duration,((e.clientX-r.left)/r.width)*audio.duration))});
  historyDrawer?.addEventListener('toggle',e=>{const b=e.currentTarget.querySelector('summary b');if(b)b.textContent=e.currentTarget.open?'−':'+'});
  document.querySelectorAll('.history-audio').forEach(b=>b.addEventListener('click',()=>{load(1,true);document.getElementById('listen')?.scrollIntoView({behavior:'smooth',block:'center'})}));
  if('mediaSession'in navigator){try{navigator.mediaSession.setActionHandler('play',()=>audio.play());navigator.mediaSession.setActionHandler('pause',()=>audio.pause());navigator.mediaSession.setActionHandler('nexttrack',()=>{if(index<queue.length-1)load(index+1,true)});navigator.mediaSession.setActionHandler('previoustrack',()=>{if(index>0)load(index-1,true)})}catch{}}
  paint(queue[0]);sync();
})();