(()=>{
  const songs=(Array.isArray(window.CMD_SAD_MUSIC)?window.CMD_SAD_MUSIC:[]).filter(song=>song.id!=='i-need-love'),groups=document.getElementById('sadGroups'),player=document.getElementById('sadPlayer'),audio=document.getElementById('sadAudio'),title=document.getElementById('sadPlayerTitle'),label=document.getElementById('sadPlayerLabel'),status=document.getElementById('sadPlayerStatus'),open=document.getElementById('sadPlayerOpen'),play=document.getElementById('sadPlay'),prev=document.getElementById('sadPrev'),next=document.getElementById('sadNext'),progress=document.getElementById('sadProgress'),bar=document.getElementById('sadProgressBar');
  const gapReady=new Promise(resolve=>{if(window.CMD_SILENT_GAP)return resolve();const s=document.createElement('script');s.src='/silent-gap.js?v=20260823-1';s.onload=resolve;s.onerror=resolve;document.head.appendChild(s)});
  let queue=[],index=-1,inGap=false,pending=-1;
  const safe=(v='')=>String(v).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
  const grouped=[];songs.forEach(song=>{let bucket=grouped.find(g=>g.name===song.group);if(!bucket){bucket={name:song.group,songs:[]};grouped.push(bucket)}bucket.songs.push(song)});
  grouped.forEach(group=>{const wrap=document.createElement('section');wrap.className='sad-group';wrap.innerHTML=`<div class="sad-group-title">${safe(group.name)}</div><div class="sad-card-grid"></div>`;const grid=wrap.querySelector('.sad-card-grid');group.songs.forEach(song=>{const card=document.createElement('article');card.className='sad-card';card.dataset.song=song.id;card.dataset.accent=song.accent||'';card.innerHTML=`<div class="sad-card-top"><span class="sad-card-era">${safe(song.era)}</span><span class="sad-version-count">${song.versions.length} ${song.versions.length===1?'version':'versions'}</span></div><h3>${safe(song.title)}</h3><p>${safe(song.summary)}</p><div class="sad-card-actions"><a class="primary" href="${safe(song.route)}">Open song →</a><button class="sad-quick-play" type="button" hidden>▶ Play</button><button class="sad-share-song" type="button">↗ Share song</button></div>`;card.querySelector('.sad-share-song')?.addEventListener('click',()=>{const data={title:song.title,text:`Listen to ${song.title}.`,url:new URL(song.route,location.origin).href};if(window.CMDShare?.nativeShare)window.CMDShare.nativeShare(data);else if(navigator.share)navigator.share(data)});grid.appendChild(card)});groups.appendChild(wrap)});
  async function exists(path){if(!path)return false;try{let res=await fetch(path,{method:'HEAD',cache:'no-store'});if(res.ok)return true;if(res.status===405){res=await fetch(path,{headers:{Range:'bytes=0-0'},cache:'no-store'});return res.ok||res.status===206}}catch{}return false}
  async function discover(){await Promise.all(songs.flatMap(song=>song.versions.map(async version=>{if(!version.audio&&await exists(version.expectedPath))version.audio=version.expectedPath})));queue=songs.flatMap(song=>song.versions.filter(v=>v.audio).map(v=>({song,version:v})));songs.forEach(song=>{const card=document.querySelector(`.sad-card[data-song="${CSS.escape(song.id)}"]`),ready=song.versions.some(v=>v.audio),button=card?.querySelector('.sad-quick-play');card?.classList.toggle('is-ready',ready);if(button){button.hidden=!ready;if(ready)button.addEventListener('click',()=>startSong(song.id))}})}
  function media(track){if(!('mediaSession'in navigator))return;try{navigator.mediaSession.metadata=new MediaMetadata({title:track.song.title,artist:'MusicSubject × Call Me Daddy',album:'When Things Got Heavy'})}catch{}}
  function paint(track){title.textContent=track.song.title;label.textContent=track.version.label;status.textContent='Playing';open.href=track.song.route;open.hidden=false;media(track)}
  function load(i,autoplay=true){if(!queue.length)return;inGap=false;pending=-1;index=(i+queue.length)%queue.length;const track=queue[index];audio.src=track.version.audio;audio.load();paint(track);player.hidden=false;document.body.classList.add('sad-player-open');if(autoplay)audio.play().catch(()=>status.textContent='Tap play to continue')}
  async function gap(){if(!queue.length)return;pending=(index+1)%queue.length;status.textContent=`Next: ${queue[pending].song.title}…`;play.textContent='⋯';await gapReady;if(!window.CMD_SILENT_GAP){load(pending,true);return}inGap=true;audio.src=window.CMD_SILENT_GAP;audio.load();audio.play().catch(()=>load(pending,true))}
  function startSong(id){const i=queue.findIndex(track=>track.song.id===id);if(i>=0)load(i,true)}
  play?.addEventListener('click',()=>{if(index<0){if(queue.length)load(0,true);return}if(inGap){audio.pause();load(pending,false);return}if(audio.paused)audio.play().catch(()=>{});else audio.pause()});prev?.addEventListener('click',()=>queue.length&&load(index<=0?queue.length-1:index-1,true));next?.addEventListener('click',()=>queue.length&&load(index+1,true));
  audio.addEventListener('play',()=>{play.textContent=inGap?'⋯':'❚❚';if(!inGap)status.textContent='Playing';window.CMDPersistentSite?.setSession(true)});audio.addEventListener('pause',()=>{if(!inGap&&!audio.ended){play.textContent='▶';status.textContent='Paused'}});audio.addEventListener('ended',()=>{if(inGap){const target=pending;inGap=false;load(target,true)}else gap()});audio.addEventListener('error',()=>{status.textContent='Skipping unavailable track…';window.setTimeout(()=>{if(inGap&&pending>=0){const target=pending;inGap=false;load(target,true)}else load(index+1,true)},500)});audio.addEventListener('timeupdate',()=>{if(!inGap&&audio.duration)bar.style.width=`${audio.currentTime/audio.duration*100}%`});progress?.addEventListener('click',e=>{if(inGap||!audio.duration)return;const r=progress.getBoundingClientRect();audio.currentTime=Math.max(0,Math.min(audio.duration,(e.clientX-r.left)/r.width*audio.duration))});
  if('mediaSession'in navigator){try{navigator.mediaSession.setActionHandler('play',()=>audio.play());navigator.mediaSession.setActionHandler('pause',()=>audio.pause());navigator.mediaSession.setActionHandler('nexttrack',()=>queue.length&&load(index+1,true));navigator.mediaSession.setActionHandler('previoustrack',()=>queue.length&&load(index-1,true))}catch{}}
  discover();
})();
