(()=>{
  const id=document.body.dataset.sadSong,songs=Array.isArray(window.CMD_SAD_MUSIC)?window.CMD_SAD_MUSIC:[],song=songs.find(s=>s.id===id),app=document.getElementById('sadSongApp');if(!song||!app)return;
  const safe=(v='')=>String(v).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));document.title=`${song.title} — MusicSubject × Call Me Daddy`;
  const shareLines={
    'locked-in-these-walls':['Three walls, one van, zero interior-design awards.','Apparently confinement has excellent acoustics.'],
    'under-watch':['Under Watch: because anxiety apparently needed a subwoofer.','Nothing says privacy like turning the feeling into a song.'],
    'seven-days-locked':['Seven days locked. Somehow the bass got parole first.','A week went in. Dubstep came out. Nobody filed the correct paperwork.'],
    'stomp-clamp':['Support me now. Bandwagon applications close after success.','Cheer during the climb or enjoy the view from the parking lot.'],
    'broke-my-mug-not-my-song':['The mug died. The song survived. Alberta winter remains a suspect.','RIP mug. Your sacrifice has been monetized into emotional bass.'],
    'friction-the-what':['You didn’t need acid. Apparently you needed this link.','Friction the What: cheaper than explaining the title sober.'],
    'couple-friends-couple-calls':['Relationships: now available in confusing audio format.','Couple friends. Couple calls. Several unanswered questions.'],
    'numbness-as-a-trap':['Numbness called itself relief and got caught lying.','Turns out feeling nothing still has consequences. In stereo.'],
    'everybody-else-less':['A fictional hater has logged on. Hide the comments.','Social-media villain origin story, now with bass.'],
    'never-come-back-down':['This song looked at rock bottom and asked if there was basement parking.','Never Come Back Down: terrible motivational slogan, decent song title.'],
    'will-to-live':['A low point wrote a song and accidentally left itself instructions.','Will to Live: when the emergency backup generator gets sub-bass.']
  };
  const ci=songs.findIndex(s=>s.id===song.id),previous=songs[(ci-1+songs.length)%songs.length],next=songs[(ci+1)%songs.length],more=song.story?`<details><summary>More story</summary><p>${safe(song.story)}</p></details>`:'';
  const sunoLinks=Array.isArray(song.sunoUrls)?song.sunoUrls.filter(Boolean):[];
  const sunoHistory=sunoLinks.length?`<details class="suno-history"><summary>${sunoLinks.length===1?'Suno source':'Suno history · '+sunoLinks.length+' generations'}</summary><div class="suno-links">${sunoLinks.map((url,i)=>`<a href="${safe(url)}" target="_blank" rel="noopener">${sunoLinks.length===1?'Open on Suno':'Suno '+(i+1)} ↗</a>`).join('')}</div></details>`:'';
  app.innerHTML=`<section class="sad-song-hero"><div class="shell sad-song-hero-inner"><a class="back" href="/sad-music/">← When Things Got Heavy</a><div class="eyebrow">${safe(song.era)} · ${safe(song.group.replace(/^\d{4}\s·\s/,''))}</div><h1>${safe(song.title)}</h1><p class="lede">${safe(song.summary)}</p><div class="actions"><a class="btn" href="/sad-music/">Collection</a><button class="btn" id="sadSongShare" type="button">↗ Share</button></div></div></section><section class="shell sad-song-main"><div class="sad-version-layout"><div class="sad-versions" id="sadVersionList"></div><aside class="sad-story"><div class="eyebrow">The story</div><h2>WHY THIS ONE EXISTS.</h2><p>${safe(song.summary)}</p>${more}${sunoHistory}<div class="sad-neighbors"><a href="${safe(previous.route)}">← ${safe(previous.title)}</a><a href="${safe(next.route)}">${safe(next.title)} →</a></div></aside></div></section>`;
  document.getElementById('sadSongShare')?.addEventListener('click',async()=>{const lines=shareLines[song.id]||[`I found ${song.title}. Things escalated.`],text=lines[Math.floor(Math.random()*lines.length)],url=new URL(song.route,location.origin).href;try{if(navigator.share){await navigator.share({title:song.title,text,url});return}await navigator.clipboard.writeText(`${text}\n${url}`);const b=document.getElementById('sadSongShare');b.textContent='✓ Copied';setTimeout(()=>b.textContent='↗ Share',1400)}catch{}});
  const versions=document.getElementById('sadVersionList');song.versions.forEach(v=>{const row=document.createElement('article');row.className='sad-version';row.dataset.version=v.id;const suno=v.sunoUrl?`<a class="sad-version-suno" href="${safe(v.sunoUrl)}" target="_blank" rel="noopener">Open this version on Suno ↗</a>`:'';row.innerHTML=`<div class="sad-version-top"><strong>${safe(v.label)}</strong><small>${safe(song.era)}</small></div><button type="button" hidden>▶ Play this version</button>${suno}`;versions.appendChild(row)});
  const player=document.getElementById('sadSongPlayer'),audio=document.getElementById('sadSongAudio'),pTitle=document.getElementById('sadSongPlayerTitle'),pLabel=document.getElementById('sadSongPlayerLabel'),pStatus=document.getElementById('sadSongPlayerStatus'),pPlay=document.getElementById('sadSongPlay'),pPrev=document.getElementById('sadSongPrev'),pNext=document.getElementById('sadSongNext'),progress=document.getElementById('sadSongProgress'),bar=document.getElementById('sadSongProgressBar'),copy=player?.querySelector('.sad-song-player-copy');
  const pOpen=document.createElement('a');pOpen.className='sad-open-song';pOpen.textContent='Open this song →';pOpen.hidden=true;copy?.appendChild(pOpen);
  const gapReady=new Promise(resolve=>{if(window.CMD_SILENT_GAP)return resolve();const s=document.createElement('script');s.src='/silent-gap.js?v=20260823-1';s.onload=resolve;s.onerror=resolve;document.head.appendChild(s)});
  let queue=[],index=-1,inGap=false,pending=-1;
  async function exists(path){if(!path)return false;try{let r=await fetch(path,{method:'HEAD',cache:'no-store'});if(r.ok)return true;if(r.status===405){r=await fetch(path,{headers:{Range:'bytes=0-0'},cache:'no-store'});return r.ok||r.status===206}}catch{}return false}
  async function discover(){await Promise.all(songs.flatMap(s=>s.versions.map(async v=>{if(!v.audio&&await exists(v.expectedPath))v.audio=v.expectedPath})));queue=songs.flatMap(s=>s.versions.filter(v=>v.audio).map(v=>({song:s,version:v})));song.versions.forEach(v=>{const button=versions.querySelector(`[data-version="${CSS.escape(v.id)}"] button`),qi=queue.findIndex(x=>x.song.id===song.id&&x.version.id===v.id);if(qi>=0&&button){button.hidden=false;button.addEventListener('click',()=>load(qi,true))}})}
  function media(t){if(!('mediaSession'in navigator))return;try{navigator.mediaSession.metadata=new MediaMetadata({title:t.song.title,artist:'MusicSubject × Call Me Daddy',album:t.version.label})}catch{}}
  function paint(t){if(!t)return;pTitle.textContent=t.song.title;pLabel.textContent=t.version.label;pStatus.textContent='Playing';pOpen.hidden=t.song.id===song.id;pOpen.href=t.song.route;media(t)}
  function sourceUrl(path){try{return new URL(path,location.href).href}catch{return path||''}}
  function syncTrackFromAudio(){
    if(inGap||!queue.length)return;
    const src=audio.currentSrc||audio.src;
    if(!src)return;
    const qi=queue.findIndex(t=>sourceUrl(t.version.audio)===src);
    if(qi<0)return;
    if(index!==qi)index=qi;
    paint(queue[index]);
  }
  function load(i,auto=true){if(!queue.length)return;inGap=false;pending=-1;index=(i+queue.length)%queue.length;const t=queue[index];audio.src=t.version.audio;audio.load();paint(t);player.hidden=false;window.CMDPersistentSite?.refreshClearance?.();if(auto)audio.play().catch(()=>pStatus.textContent='Tap play to continue')}
  async function gap(){if(!queue.length)return;pending=(index+1)%queue.length;pStatus.textContent=`Next: ${queue[pending].song.title}…`;pPlay.textContent='⋯';await gapReady;if(!window.CMD_SILENT_GAP){load(pending,true);return}inGap=true;audio.src=window.CMD_SILENT_GAP;audio.load();audio.play().catch(()=>load(pending,true))}
  pPlay?.addEventListener('click',()=>{if(index<0){const first=queue.findIndex(x=>x.song.id===song.id);if(first>=0)load(first,true);return}if(inGap){audio.pause();load(pending,false);return}if(audio.paused)audio.play().catch(()=>{});else audio.pause()});pPrev?.addEventListener('click',()=>queue.length&&load(index-1,true));pNext?.addEventListener('click',()=>queue.length&&load(index+1,true));
  audio.addEventListener('loadedmetadata',syncTrackFromAudio);
  audio.addEventListener('play',()=>{syncTrackFromAudio();pPlay.textContent=inGap?'⋯':'❚❚';if(!inGap)pStatus.textContent='Playing';window.CMDPersistentSite?.setSession(true);window.CMDPersistentSite?.refreshClearance?.()});audio.addEventListener('pause',()=>{if(!inGap&&!audio.ended){pPlay.textContent='▶';pStatus.textContent='Paused'}});audio.addEventListener('ended',()=>{if(inGap){const target=pending;inGap=false;load(target,true)}else gap()});audio.addEventListener('timeupdate',()=>{if(!inGap&&audio.duration)bar.style.width=`${audio.currentTime/audio.duration*100}%`});progress?.addEventListener('click',e=>{if(inGap||!audio.duration)return;const r=progress.getBoundingClientRect();audio.currentTime=Math.max(0,Math.min(audio.duration,(e.clientX-r.left)/r.width*audio.duration))});
  if('mediaSession'in navigator){try{navigator.mediaSession.setActionHandler('play',()=>audio.play());navigator.mediaSession.setActionHandler('pause',()=>audio.pause());navigator.mediaSession.setActionHandler('nexttrack',()=>queue.length&&load(index+1,true));navigator.mediaSession.setActionHandler('previoustrack',()=>queue.length&&load(index-1,true))}catch{}}
  discover();
})();