(()=>{
  const id=document.body.dataset.sadSong,songs=Array.isArray(window.CMD_SAD_MUSIC)?window.CMD_SAD_MUSIC:[],song=songs.find(s=>s.id===id),app=document.getElementById('sadSongApp');if(!song||!app)return;
  const safe=(v='')=>String(v).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));document.title=`${song.title} — MusicSubject × Call Me Daddy`;
  const ci=songs.findIndex(s=>s.id===song.id),previous=songs[(ci-1+songs.length)%songs.length],next=songs[(ci+1)%songs.length];
  const more=song.story?`<details><summary>More story</summary><p>${safe(song.story)}</p></details>`:'';
  app.innerHTML=`<section class="sad-song-hero"><div class="shell sad-song-hero-inner"><a class="back" href="/sad-music/">← When Things Got Heavy</a><div class="eyebrow">${safe(song.era)} · ${safe(song.group.replace(/^\d{4}\s·\s/,''))}</div><h1>${safe(song.title)}</h1><p class="lede">${safe(song.summary)}</p><div class="actions"><a class="btn" href="/sad-music/">Collection</a></div></div></section><section class="shell sad-song-main"><div class="sad-version-layout"><div class="sad-versions" id="sadVersionList"></div><aside class="sad-story"><div class="eyebrow">The story</div><h2>WHY THIS ONE EXISTS.</h2><p>${safe(song.summary)}</p>${more}<div class="sad-neighbors"><a href="${safe(previous.route)}">← ${safe(previous.title)}</a><a href="${safe(next.route)}">${safe(next.title)} →</a></div></aside></div></section>`;
  const versions=document.getElementById('sadVersionList');song.versions.forEach(v=>{const row=document.createElement('article');row.className='sad-version';row.dataset.version=v.id;row.innerHTML=`<div class="sad-version-top"><strong>${safe(v.label)}</strong><small>${safe(song.era)}</small></div><button type="button" hidden>▶ Play this version</button>`;versions.appendChild(row)});
  const player=document.getElementById('sadSongPlayer'),audio=document.getElementById('sadSongAudio'),pTitle=document.getElementById('sadSongPlayerTitle'),pLabel=document.getElementById('sadSongPlayerLabel'),pStatus=document.getElementById('sadSongPlayerStatus'),pPlay=document.getElementById('sadSongPlay'),pPrev=document.getElementById('sadSongPrev'),pNext=document.getElementById('sadSongNext'),progress=document.getElementById('sadSongProgress'),bar=document.getElementById('sadSongProgressBar');let playable=[],index=-1;
  async function exists(path){if(!path)return false;try{let r=await fetch(path,{method:'HEAD',cache:'no-store'});if(r.ok)return true;if(r.status===405){r=await fetch(path,{headers:{Range:'bytes=0-0'},cache:'no-store'});return r.ok||r.status===206}}catch{}return false}
  async function discover(){await Promise.all(song.versions.map(async v=>{if(!v.audio&&await exists(v.expectedPath))v.audio=v.expectedPath}));playable=song.versions.filter(v=>v.audio);song.versions.forEach(v=>{const button=versions.querySelector(`[data-version="${CSS.escape(v.id)}"] button`);if(v.audio&&button){button.hidden=false;button.addEventListener('click',()=>load(playable.findIndex(x=>x.id===v.id),true))}})}
  function media(v){if(!('mediaSession'in navigator))return;try{navigator.mediaSession.metadata=new MediaMetadata({title:song.title,artist:'MusicSubject × Call Me Daddy',album:v.label})}catch{}}
  function load(i,auto=true){if(!playable.length)return;index=(i+playable.length)%playable.length;const v=playable[index];audio.src=v.audio;audio.load();pTitle.textContent=song.title;pLabel.textContent=v.label;pStatus.textContent=auto?'Loading…':'Ready';player.hidden=false;media(v);if(auto)audio.play().catch(()=>pStatus.textContent='Tap play to continue')}
  pPlay?.addEventListener('click',()=>{if(index<0){if(playable.length)load(0,true);return}if(audio.paused)audio.play().catch(()=>{});else audio.pause()});pPrev?.addEventListener('click',()=>playable.length&&load(index-1,true));pNext?.addEventListener('click',()=>playable.length&&load(index+1,true));
  audio.addEventListener('play',()=>{pPlay.textContent='❚❚';pStatus.textContent='Playing';window.CMDPersistentSite?.setSession(true)});audio.addEventListener('pause',()=>{if(!audio.ended){pPlay.textContent='▶';pStatus.textContent='Paused'}});audio.addEventListener('ended',()=>{if(playable.length>1)load(index+1,true);else{pPlay.textContent='▶';pStatus.textContent='Finished'}});audio.addEventListener('timeupdate',()=>{if(audio.duration)bar.style.width=`${audio.currentTime/audio.duration*100}%`});progress?.addEventListener('click',e=>{if(!audio.duration)return;const r=progress.getBoundingClientRect();audio.currentTime=Math.max(0,Math.min(audio.duration,(e.clientX-r.left)/r.width*audio.duration))});discover();
})();